version: '3.8'

services:
  postgres_test:
    image: postgres:15
    container_name: postgres_test
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: petconnect-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: petconnectdatabase
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    restart: always

  petconnect-test:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: petconnect-test
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_test:5432/petconnect-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: petconnectdatabase
    depends_on:
      postgres_test:
        condition: service_healthy
    command: mvn test

volumes:
  pgdata-test:
